# profile default 
spring:
  profiles.active: dev
---
# HTTP Server
server:
  port: 8181 # HTTP (Tomcat) port

#profile config  
spring:
  application:
    name: user-microservice-1
  profiles: dev

#activemq config
  activemq:
    broker-url: tcp://localhost:61616
    password: admin
    user:  admin

#mysql config    
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost/mt_user_microservice_dev
    driverClassName: com.mysql.jdbc.Driver 

#jpa config
  jpa:
    hibernate:
      ddlAuto: update
      namingStrategy: org.hibernate.cfg.EJB3NamingStrategy
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
    
#activemq queue for logging   
logging:
  queue: 
   name: logging.queue

#activemq topic for user events   
user:
  topic: 
   name: user.event.topic
  
# Discovery Server Access  
eureka:
  instance:
    virtual-host-name: user-microservice 
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.instance_id:1}
    client:
        serviceUrl:
            defaultZone: http://localhost:8761/eureka/

#modifying  
info:
  app:
    version: 0.0.1-SNAPSHOT
    name: ${spring.application.name}
    profile: ${spring.profiles.active}
    database: ${spring.datasource.url}
---
# HTTP Server
server:
  port: 8181 # HTTP (Tomcat) port

#profile config  
spring:
  application:
    name: user-microservice-${random.value}
  profiles: prod

#activemq config
  activemq:
    broker-url: tcp://localhost:61616
    password: admin
    user:  admin

#mysql config    
  datasource:
    username: root
    password:
    url: jdbc:mysql://localhost/mt_user_microservice_prod
    driverClassName: com.mysql.jdbc.Driver 

#jpa config
  jpa:
    hibernate:
      ddlAuto: update
      namingStrategy: org.hibernate.cfg.EJB3NamingStrategy
      dialect: org.hibernate.dialect.MySQL5Dialect
    show-sql: false
    
#activemq queue for logging   
logging:
  queue: 
   name: logging.queue

#activemq topic for user events   
user:
  topic: 
   name: user.event.topic
   
# Discovery Server Access  
eureka:
  instance:
    virtual-host-name: user-microservice 
    metadata-map:
      instanceId: ${spring.application.name}:${spring.application.instance_id:${random.value}}
  client:
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/